Testing: Post-Install test docs
rocky-linux/wiki.rockylinux.org pull request #15
Opened 2022-04-28 22:03 UTC by lumarel

This PR will add the post install tests to the testing documenation.

Tracking issue: fixes #14

2022-06-24 02:34 UTC, akatch requested changes
I left a number of comments; the only blocking issue I see is a link to the ESXi hack you mentioned for multimonitor support. All links work and all other content looks good.

2022-06-24 02:34 UTC, akatch commented on docs/team/testing/QA/Testcase_Post_Artwork_and_Assets.md
> +1. Aquire access to either a baremetal machine or a VM host, to install a new machine
Should be `Acquire`

2022-06-24 02:34 UTC, akatch commented on docs/team/testing/QA/Testcase_Post_Keyboard_Layout.md
> +- Aquire access to either a baremetal machine or a VM host, to install a new machine
As above, should be `Acquire`

2022-06-24 02:34 UTC, akatch commented on docs/team/testing/QA/Testcase_Post_Multimonitor_Setup.md
> +You will need either a machine which can be reinstalled with multiple screens, or a virtualization software which is capable of providing multiple screens (like VMware Workstation, but there is also
Any chance you could provide a link to the ESXi solution?

2022-06-24 02:34 UTC, akatch commented on docs/team/testing/QA/Testcase_Post_System_Services.md
> +1. Aquire access to either a baremetal machine or a VM host, to install a new machine
As above, should be `Acquire`

2022-06-24 02:34 UTC, akatch commented on docs/team/testing/QA/Testcase_Post_System_Services.md
> +1. Aquire access to either a baremetal machine or a VM host, to install a new machine
Also it occurs to me that this section seems to recur several times and might benefit from being a template snippet, but I'll leave that up to you.

2022-06-24 02:34 UTC, akatch commented on docs/team/testing/QA/Testcase_Post_Module_Streams.md
> +2. Get a list of all module streams and compare it to the [stream list from RHEL](https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle) and to the source in [Git source repo](
`rocky-module-defaults` exists but is basically empty as of this writing. Do we need to point users somewhere else or do we expect that this repo will be populated eventually?

2022-06-29 23:07 UTC, lumarel commented on docs/team/testing/QA/Testcase_Post_Module_Streams.md
> +2. Get a list of all module streams and compare it to the [stream list from RHEL](https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle) and to the source in [Git source repo](
It's not empty, please look at the individual branches for the individual releases 🙂

2022-06-29 23:31 UTC, tcooper commented on docs/team/testing/QA/Testcase_Post_Application_Functionality.md
> +  ver: 8
All of the Testcase_* files in this PR have a consistent mismatch between the `ver: 8` in the header and the links in the error and info pullouts at the top of the file. This is caused by the template being created before we split into two versions. A general solution needs to be decided. For Testcases that are valid for both r8 and r8 I suggest the `ver: 8 and 9` be used in the header and any use of the variable in the body be reworded accordingly. When separated Testcase_ body is required for r8 and r8 then separate files can/must be used and the version *must* be  included in the filename to allow the magic linking to work.

2022-06-29 23:33 UTC, tcooper commented on docs/team/testing/release_criteria/r8/8_release_criteria.md
>  author: Trevor Cooper
Since you're already likely to make changes for this PR by all means modify the author: to include yourself.

2022-06-30 22:31 UTC, lumarel commented on docs/team/testing/QA/Testcase_Post_Application_Functionality.md
> +  ver: 8
I'm not sure if I understand that correctly, did you already implement this somewhere, so I can just copy that, or is this how we want to do it from now on? 🙂
Should `ver: 8 and 9` be in the `rc.ver` and then I should reference that whereever needed in the files?

2022-06-30 22:34 UTC, lumarel commented on docs/team/testing/release_criteria/r8/8_release_criteria.md
>  author: Trevor Cooper
You're for sure right with this, thank you for correcting me!

2022-07-01 15:40 UTC, lumarel commented on docs/team/testing/QA/Testcase_Post_Application_Functionality.md
> +  ver: 8
Okay that was pretty well explained, thank you!
I will see what I can do and change it to something more appropriate 👍🏻

2022-07-02 23:00 UTC, lumarel commented on docs/team/testing/QA/Testcase_Post_Application_Functionality.md
> +  ver: 8
@tcooper I tried to work with Jinja2 in the links, but that breaks them, also templates with variables from the individual page doesn't work, so this is the best solution I got for now, I hope this is something like what you also had in mind, it's something I'm fine with tbh 🙂
If this looks good in this way, I can wip up another PR where I will change that for all current Testcase descriptions 👌🏻

2022-07-04 04:57 UTC, tcooper approved these changes
Looks good in test wiki box. Thanks for all the work!

2022-07-05 02:43 UTC, akatch approved these changes
Looks awesome, thanks Lukas!

2022-07-05 02:43 UTC, akatch commented on docs/team/testing/QA/Testcase_Post_Application_Functionality.md
> +    This Testcase applies the following versions of {{ rc.prod }}: {% for version in rc.ver %}{{ version }}{% if not loop.last %}, {% endif %}{% endfor %}
Nonblocking, but I believe `{{ rc.ver | join(", ") }}` would also work

2022-07-05 02:51 UTC, merged