Testing: Installer Requirements
rocky-linux/wiki.rockylinux.org pull request #28
Opened 2022-05-08 17:36 UTC by akatch

This PR will add documentation for the test cases covering [Installer Requirements](https://wiki.rockylinux.org/team/testing/release_criteria/#installer-requirements). Fixes #27 when complete.

2022-05-20 03:07 UTC, tcooper commented
@akatch Comments...
- I like the addition of the include files for repeating content. That is a pattern we should try to keep leveraging where ever possible.
- Leveraging existing content is a good idea as well. There may be more cleanup to do here after more docs land.
- Let's think hard about if/how to include screenshots with particular attention perhaps to understanding if / how we might present them in a way similar to how openQA does natively (ie. thumbnail grid and clickable zoom). Perhaps there is a mkdocs plugin that can be leveraged for this?

2022-06-12 16:20 UTC, lumarel reviewed
Beside the merge conflict with my PR these few links need a update 🙂

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Bootloader_Disk_Selection.md
> +    This test case is associated with the [Release_Criteria#Bootloader Disk Selection](../release_criteria.md#bootloader-disk-selection) release criterion. If you are doing release validation testing
Link doesn't work anymore after restructuring

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Disk_Layouts.md
> +    This test case is associated with the [Release_Criteria#Disk Layouts](../release_criteria.md#disk-layouts) release criterion. If you are doing release validation testing, a failure of this test c
As well link, after restructure

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Firmware_RAID.md
> +    This test case is associated with the [Release_Criteria#Firmware RAID](../release_criteria.md#firmware-raid) release criterion. If you are doing release validation testing, a failure of this test
As well link, after restructure

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Installation_Interfaces.md
> +    This test case is associated with the [Release_Criteria#Installation Interfaces](../release_criteria.md#installation-interfaces) release criterion. If you are doing release validation testing, a
As well link, after restructure

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Installer_Help.md
> +    This test case is associated with the [Release_Criteria#Installer Help](../release_criteria.md#installer-help) release criterion. If you are doing release validation testing, a failure of this te
As well link, after restructure

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Installer_Translations.md
> +    This test case is associated with the [Release_Criteria#Installer Translations](../release_criteria.md#installer-translations) release criterion. If you are doing release validation testing, a fa
As well link, after restructure

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Kickstart_Installation.md
> +    This test case is associated with the [Release_Criteria#Kickstart Installation](../release_criteria.md#kickstart-installation) release criterion. If you are doing release validation testing, a fa
As well link, after restructure

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Minimal_Installation.md
> +    This test case is associated with the [Release_Criteria#Minimal Installation](../release_criteria.md#minimal-installation) release criterion. If you are doing release validation testing, a failur
As well link, after restructure

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Network_Attached_Storage.md
> +    This test case is associated with the [Release_Criteria#Network Attached Storage](../release_criteria.md#network-attached-storage) release criterion. If you are doing release validation testing,
As well link, after restructure

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Packages_Installer_Sources.md
> +    This test case is associated with the [Release_Criteria#Packages and Installer Sources](../release_criteria.md#packages-installer-sources) release criterion. If you are doing release validation t
As well link, after restructure

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Storage_Volume_Resize.md
> +    This test case is associated with the [Release_Criteria#Storage Volume Resize](../release_criteria.md#storage-volume-resize) release criterion. If you are doing release validation testing, a fail
As well link, after restructure

2022-06-12 16:20 UTC, lumarel commented on docs/team/testing/QA/Testcase_Update_Image.md
> +    This test case is associated with the [Release_Criteria#Update Image](../release_criteria.md#update-image) release criterion. If you are doing release validation testing, a failure of this test c
As well link, after restructure

2022-07-08 06:43 UTC, akatch commented
The broken links should all be resolved with my latest commit, as well as a couple of other missing ones AutoLinksPlugin pointed out for me ✨

2022-07-08 16:36 UTC, lumarel requested changes
It's a few very minor thingies 🙂

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Installer_Help.md
> +- `anaconda_help`
Here as well a empty line is missing

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Installer_Translations.md
> +- `install_asian_language`
Here as well a empty line is missing

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Kickstart_Installation.md
> +1. Provide a local Kickstart file by supplying the GRUB boot option `inst.ks=file:/path/to/local.ks` or a remote Kickstart file by supplying the GRUB boot option `inst.ks=https://dl.rockylinux.org/re
You can also just use a 2nd seperate Media (USB-Stick, ISO, ...) and LABEL it with `OEMDRV` (with the file called `ks.cfg`) and it will pick up the kickstart file automatically on boot 🙂
_lazy people edition_

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Kickstart_Installation.md
> +- `install_kickstart_nfs`
Here as well a empty line is missing

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Minimal_Installation.md
> +- `install_minimal`
Here as well a empty line is missing

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Packages_Installer_Sources.md
> +- server
Here as well a empty line is missing

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Packages_Installer_Sources.md
> +- workstation
Here as well a empty line is missing

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Packages_Installer_Sources.md
> +- `install_packageset_server`
Here as well a empty line is missing

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Storage_Volume_Resize.md
> +- `install_delete_partial`
Here as well a empty line is missing

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Update_Image.md
> +- `install_scsi_updates_img`
Here as well a empty line is missing

2022-07-08 16:36 UTC, lumarel commented on docs/team/testing/QA/Testcase_Update_Image.md
> +[Fedora QA:Testcase Anaconda updates.img via local media](https://fedoraproject.org/wiki/QA:Testcase_Anaconda_updates.img_via_local_media)
These links might need either separators or a `<br>`

2022-07-08 19:48 UTC, lumarel commented on docs/team/testing/QA/Testcase_Update_Image.md
> +- `install_scsi_updates_img`
This one got missing 👀

2022-07-08 23:02 UTC, lumarel approved these changes
Thank you for the fixes, now it looks good to me! 👀

2022-07-08 23:49 UTC, nazunalika approved these changes

2022-07-09 00:01 UTC, merged