add Testcase_VNC_Graphics_Mode
rocky-linux/wiki.rockylinux.org pull request #37
Opened 2022-06-23 21:03 UTC by tcooper

This PR will add a testcase for r9 to document validation of VNC Graphics mode installations.

Resolves #36

2022-06-23 21:48 UTC, lumarel commented on docs/team/testing/QA/Testcase_VNC_Graphics_Mode.md
> +3. Obtain access to remote system with TigerVNC installed to use for VNC connection.
I don't think it really has to be TigerVNC, just a VNC client, right?

2022-06-24 02:53 UTC, tcooper commented on docs/team/testing/QA/Testcase_VNC_Graphics_Mode.md
> +3. Obtain access to remote system with TigerVNC installed to use for VNC connection.
Yes... I believe any VNC client will work. `tigervnc` and `vinagre` are the Rocky provided VNC clients. I'll reword the item suggest `tigervnc` and/or `vinagre` as being provided by Rocky but indicated that any VNC client should work.

2022-06-24 03:10 UTC, akatch requested changes
In addition to my one comment, I think you also need to add the VNC Graphics Mode page to qa_test_cases.md.

2022-06-24 03:10 UTC, akatch commented on docs/team/testing/QA/Testcase_Custom_Boot_Methods_Boot_Iso.md
> +This is to verify that the Anaconda installer starts correctly when booting from the Rocky Linux boot.iso using a custom .
A custom what? I think you a word :)

2022-06-24 03:35 UTC, tcooper commented on docs/team/testing/QA/Testcase_Custom_Boot_Methods_Boot_Iso.md
> +This is to verify that the Anaconda installer starts correctly when booting from the Rocky Linux boot.iso using a custom .
Thanks @akatch should be taken care of.

2022-06-24 04:12 UTC, akatch approved these changes

2022-07-02 05:18 UTC, merged